template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "torn1244"
__REPO__ = "lang-fit"
__UND2C__ = "fit"
__UNDEFINED__ = "Tornedalen Finnish"
__UND__ = "fit"
