template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "torn1244"
__REPO__ = "lang-fit"
__UND2C__ = "fit"
__UNDEFINED__ = "Tornedalen Finnish"
__UND__ = "fit"
