template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "torn1244"
__REPO__ = "lang-fit"
__UND2C__ = "fit"
__UNDEFINED__ = "Tornedalen Finnish"
__UND__ = "fit"
